//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANEXOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANEXOS()
        {
            this.RADICACIONES = new HashSet<RADICACIONES>();
        }
    
        public int ID_ANEXO { get; set; }
        public string NOMBRE_ANEXO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADICACIONES> RADICACIONES { get; set; }
    }
}
namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPENDENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPENDENCIA()
        {
            this.RADICACIONES = new HashSet<RADICACIONES>();
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int ID_DEPENDENCIA { get; set; }
        public string NOMBRE_DEPENDENCIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADICACIONES> RADICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADICACIONES
    {
        public int ID_RADICACION { get; set; }
        public string ASUNTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> FOLIOS { get; set; }
        public Nullable<int> CANTIDAD_ANEXOS { get; set; }
        public int ID_USUARIOS_FK { get; set; }
        public int ID_USUARIO_EXT_FK { get; set; }
        public int ID_ANEXO_FK { get; set; }
        public int ID_DEPENDENCIA_FK { get; set; }
        public int ID_TIPO_DOC { get; set; }
    
        public virtual ANEXOS ANEXOS { get; set; }
        public virtual DEPENDENCIA DEPENDENCIA { get; set; }
        public virtual TIPO_DOCUMENTOS TIPO_DOCUMENTOS { get; set; }
        public virtual USUARIO_EXTERNO USUARIO_EXTERNO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ACCESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_ACCESO()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int ID_TIPO_ACCESO { get; set; }
        public string NOMBRE_TIPO_ACCESO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DOCUMENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_DOCUMENTOS()
        {
            this.RADICACIONES = new HashSet<RADICACIONES>();
        }
    
        public int ID_TIPO_DOC { get; set; }
        public string NOMBRE_TIPO_DOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADICACIONES> RADICACIONES { get; set; }
    }
}
namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_EXTERNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO_EXTERNO()
        {
            this.RADICACIONES = new HashSet<RADICACIONES>();
        }
    
        public int ID_USUARIO_EXT { get; set; }
        public string DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string PERSONA_ENCARGADA { get; set; }
        public string CARGO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADICACIONES> RADICACIONES { get; set; }
    }
}
namespace ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.RADICACIONES = new HashSet<RADICACIONES>();
        }
    
        public int ID_USUARIOS { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public int ID_TIPO_ACCESO_FK { get; set; }
        public int ID_DEPENDENCIA_FK { get; set; }
    
        public virtual DEPENDENCIA DEPENDENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADICACIONES> RADICACIONES { get; set; }
        public virtual TIPO_ACCESO TIPO_ACCESO { get; set; }
    }
}
