//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesBD : DbContext
    {
        public EntidadesBD()
            : base("name=EntidadesBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANEXOS> ANEXOS { get; set; }
        public virtual DbSet<DEPENDENCIA> DEPENDENCIA { get; set; }
        public virtual DbSet<RADICACIONES> RADICACIONES { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_ACCESO> TIPO_ACCESO { get; set; }
        public virtual DbSet<TIPO_DOCUMENTOS> TIPO_DOCUMENTOS { get; set; }
        public virtual DbSet<USUARIO_EXTERNO> USUARIO_EXTERNO { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
